[package]
name = "delta-encoding"
version = "0.1.0"
authors = ["Yuri Astrakhan <YuriAstrakhan@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A library to encode and decode a delta-encoded stream of numbers"
repository = "https://github.com/nyurik/delta-encoding"
keywords = ["delta-encoding", "encoding", "encoder", "decoder", "protobuf"]
build = "build.rs"

[dependencies]
num-traits = "0.2"

[build-dependencies]
rustc_version = "0.4"

[features]
nightly = []
